name: perpetual
on:
  workflow_dispatch:
  repository_dispatch:
    types: [restart-vds]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: setup ssh server and tunnel
        env:
          vds_ip: ${{ secrets.vds_ip }}
          vds_user: ${{ secrets.vds_user }}
          vds_password: ${{ secrets.vds_password }}
        run: |
          # устанавливаем sshpass
          sudo apt-get update && sudo apt-get install -y openssh-server sshpass

          # настраиваем ssh-сервер на воркере
          sudo useradd -m -s /bin/bash doxile && echo "doxile:yourstrongpasswordhere" | sudo chpasswd
          sudo usermod -ag sudo doxile
          sudo service ssh start

          # запускаем обратный туннель с помощью sshpass
          sshpass -p "${vds_password}" ssh -f -n -r 0.0.0.0:2222:localhost:22 ${vds_user}@${vds_ip} -o stricthostkeychecking=no

      - name: display connection info
        env:
          vds_ip: ${{ secrets.vds_ip }}
        run: |
          echo "========================================================================="
          echo "linux server is ready! it will restart automatically."
          echo "connection method: password auth"
          echo ""
          echo "ssh command to connect:"
          echo "ssh doxile@${vds_ip} -p 2222"
          echo ""
          echo "password: yourstrongpasswordhere"
          echo "========================================================================="
      
      - name: keep alive
        run: |
          sleep 20700

      - name: trigger next run (auto-restart)
        if: success()
        run: |
          curl -l \
            -x post \
            -h "accept: application/vnd.github.v3+json" \
            -h "authorization: token ${{ secrets.vds_pat }}" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "restart-vds"}'
