name: Enable Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      # шаг 1: настраиваем ssh-сервер на воркере и запускаем туннель
      - name: Setup SSH Server and Tunnel
        env:
          VDS_IP: ${{ secrets.VDS_IP }}
          VDS_USER: ${{ secrets.VDS_USER }}
          VDS_SSH_PRIVATE_KEY: ${{ secrets.VDS_SSH_PRIVATE_KEY }}
        run: |
          # настраиваем ssh-сервер
          sudo apt-get update && sudo apt-get install -y openssh-server
          # !!! не забудь поменять пароль !!!
          sudo useradd -m -s /bin/bash doxile && echo "doxile:testing" | sudo chpasswd
          sudo usermod -aG sudo doxile
          sudo service ssh start

          # настраиваем ssh-клиент для туннеля
          mkdir -p ~/.ssh
          echo "${VDS_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # добавляем vds в известные хосты
          ssh-keyscan -H "${VDS_IP}" >> ~/.ssh/known_hosts

          # запускаем обратный туннель в фоновом режиме
          ssh -f -N -R 0.0.0.0:2222:localhost:22 ${VDS_USER}@${VDS_IP}
          echo "Tunnel process started in the background."

      # шаг 2: выводим информацию для подключения
      - name: Display Connection Info
        env:
          VDS_IP: ${{ secrets.VDS_IP }}
        run: |
          echo "========================================================================="
          echo "Tunnel should be active now."
          echo "If it fails, check your keys and VDS SSH settings."
          echo ""
          echo "SSH command to connect:"
          echo "ssh doxile@${VDS_IP} -p 2222"
          echo ""
          echo "Password: YourStrongPasswordHere (the one you set)"
          echo "========================================================================="
      
      # шаг 3: рабочий цикл
      - name: Keep Alive
        run: |
          sleep 21000 # ~5 часов 50 минут
