name: Tunnel Runner

on:
  workflow_dispatch:

jobs:
  setup-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH Keys and Display Instructions
        run: |
          ssh-keygen -t rsa -b 4096 -f github_action_key -N ""
          PRIVATE_KEY=$(cat github_action_key)
          PUBLIC_KEY=$(cat github_action_key.pub)
          
          echo "====================== ВНИМАНИЕ! РАЗОВАЯ НАСТРОЙКА ======================"
          echo "1. В секретах твоего репозитория GitHub создай секрет с именем 'VDS_SSH_PRIVATE_KEY'."
          echo "2. Вставь в него ВЕСЬ текст ниже (от '-----BEGIN...' до '...END RSA PRIVATE KEY-----'):"
          echo "----------------------------- ПРИВАТНЫЙ КЛЮЧ -----------------------------"
          echo "$PRIVATE_KEY"
          echo "-----------------------------------------------------------------------"
          echo "3. Подключись к своему VDS и выполни эту команду, чтобы добавить публичный ключ:"
          echo 'echo "'"$PUBLIC_KEY"'" >> /home/tunneler/.ssh/authorized_keys'
          echo "-----------------------------------------------------------------------"
          echo "4. После этого останови (Cancel) этот запуск и удали этот YML файл."
          echo "   Затем создай новый YML файл с кодом из 'Этапа 4' гайда."
          echo "======================================================================="
          
          sleep 3600
